---
version: "3"
services:
  vpn:
    image: wireguard:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/wireguard:/data/wireguard:Z
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 8.8.8.8 # Your VPN's DNS Server, not this one
    ports:
      - 80:80
      - 443:443
      #- 8888:8888 # OR use proxy http://172.20.0.20:8888
    networks:
      service:
        ipv4_address: 172.20.0.20
    restart: unless-stopped

networks:
  service:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
